-- CREATE THE APPLICATION SCHEMA
CREATE SCHEMA IF NOT EXISTS team;

--CREATE THE MAIN TABLE THAT WILL STORE ALL DREAMIX MEMBERS
CREATE SEQUENCE IF NOT EXISTS team.member_id_seq;

CREATE TABLE IF NOT EXISTS team.MEMBER (
                ID INTEGER NOT NULL DEFAULT nextval('team.member_id_seq'),
                EMAIL VARCHAR NOT NULL,
                FIRST_NAME VARCHAR NOT NULL,
                LAST_NAME VARCHAR NOT NULL,
                PHOTO_URL VARCHAR NOT NULL,
				HIRE_DATE DATE NOT NULL,
                CONSTRAINT member_pk PRIMARY KEY (ID)
);