spring:
  profiles:
    active: native
---
spring:
  profiles: native
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:config, classpath:/config/{application}/{profile}
---
spring:
  profiles: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/TEST_REPO
          searchPaths: 'config-mservice-properties/{application}/{profile}'
          username: USERNAME
          password: PASSWORD